# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_P0YMl4hYr1EkYkPelHDqltwJdoqkG99
"""

PreviousSemester = input("Please enter the courses you have taken previously with letter grades: ")
if PreviousSemester.count(":") != (PreviousSemester.count(";")+1) :
  print("Invalid input")
else:
  CurrentSemester = input("Please enter the courses you have taken this semester with letter grades: ")
  if CurrentSemester.count(":") != (CurrentSemester.count(";")+1) :
    print("Invalid input")
  else :
    CourseTobeChecked = input("Please enter the course you want to check: ")
    if not CourseTobeChecked in CurrentSemester :
      print("You didn't take",CourseTobeChecked,"this semester.")
    else:
      PreviousSemester_list= PreviousSemester.split(";")
      CurrentSemester_list = CurrentSemester.split(";")
      for a in CurrentSemester_list :
        if CourseTobeChecked in a :
          a = a.split(":")
          if not "F" in a[1] and not "f" in a[1] :
            print("You can choose between S and",a[1].capitalize(),"for",CourseTobeChecked)
          elif not CourseTobeChecked in PreviousSemester :
            print("Your grade for",CourseTobeChecked,"is U.")
          else:
            for i in PreviousSemester_list:
              if CourseTobeChecked in i :
                i = i.split(":")
                if "U" in i[1] or "u" in i[1] :
                  print("Your grade for",CourseTobeChecked,"is U.")
                else:
                  print("Your grade for",CourseTobeChecked,"is F.")



            

#Hagverdi Ibrahimli
#00030014