# -*- coding: utf-8 -*-
"""ihagverdi_the1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8zc8fnhnDLll1MyEgasrMVPeiUWyO29
"""

#Input
InitialDataGB =float(input("Please enter your internet quota (GB): "))
minofVideowatched =float(input("Please enter your total video viewing time in minutes: "))
textssent =float(input("Please enter the number of messages you send: "))

costofvideos_mb = minofVideowatched*7.7
costoftexts_kb = textssent*1.7


costofvideos_gb = costofvideos_mb/1024
costoftexts_gb = costoftexts_kb/1048576

remainingQuota = InitialDataGB-(costofvideos_gb+costoftexts_gb)

#REMAINING STUFF
totalVideoinminutes = (remainingQuota*1024)/7.7
hours = totalVideoinminutes/60

minutes = (hours-int(hours))*60

seconds = (minutes-int(minutes))*60

print("Your remaining internet quota is",format(remainingQuota,".2f"),"GB(s).")
print("You can watch video for",int(hours),"hour(s),",int(minutes),"minute(s)","and",format(seconds,".2f"),"second(s).")
#StudentName: Hagverdi Ibrahimli
#StudentID: 00030014